name: auto-release

on:
    push:
        tags:
            - 'v*'

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set environment variables
              run: |
                  echo "VERSION=`echo ${GITHUB_REF#refs/*/}`" >> $GITHUB_ENV

            - name: Replace variables
              run: |
                  sed -i -e 's/${version}/'"${{env.VERSION}}"'/g' resourcepack/pack.mcmeta

            - name: Zip resourcepack
              uses: edgarrc/action-7z@v1
              with:
                  args: 7z a "HaruhiismAdditionalMusicPack-${{env.VERSION}}.zip" ./resourcepack/* LICENSE

            - name: Github release
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      *.zip
